version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
        name: install global dependencies
        command: npm install -g nyc coveralls
      - run: npm test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["10.22.0", "12.18.3", "14.10.1"]
              os: ["linux"]
