version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install global dependencies
          command: sudo npm install -g nyc coveralls
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Run test
          command: npm run coverage
      - run: 
          name: Report coveralls
          command: npm run coveralls

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["10.22.0", "12.18.3", "14.10.1"]
              os: ["linux"]
